Check why/if ua.tests.doc require jdt/pde
eclipse-platform/eclipse.platform.ua pull request #97
Opened 2023-02-13 13:42 UTC by laeubi

2023-02-13 13:44 UTC, laeubi commented
@akurtakov @vogella anyone knows *what* actually these tests "test" and why we have a requirement on JDT/PDE here?

2023-02-13 13:54 UTC, laeubi commented
Only failing test is `org.eclipse.ua.tests.doc.internal.linkchecker.ApiDocTest` that seem to test some converns from JDT/PDE I think we have two options here:

1. remove references and don't care about PDE/JDT
2. PDE/JDT can copy the test and check their parts directly in the repo

the test iself seems self-contained enough for this.

2023-02-13 14:01 UTC, akurtakov commented
I would be fine with such approach for testing.

2023-02-15 07:53 UTC, iloveeclipse requested changes

2023-02-15 07:53 UTC, iloveeclipse commented on org.eclipse.ua.tests.doc/src/org/eclipse/ua/tests/doc/internal/linkchecker/ApiDocTest.java
> +			// FIXME why do we test JDT + PDE here ?!?
The ApiDocTest that run **on jenkins** is meaningless. It is supposed to run in full SDK build and test that all the API we ship in SDK doesn't have broken references - and that needs both JDT / PDE.

So if you want fix jenkins build, please **conditionally** disable it for jenkins.

2023-07-03 13:13 UTC, closed without merging